# Имя workflow
name: My workflow
 
# Запуск на определенных тригерах и ветках
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
# Задачи
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test
      run: mvn clean install

  deploy:
    needs: build
    runs-on: ubuntu-latest

# Устанавливаем соединение по SSH с виртуальной машиной
    steps:
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_SECRET_KEY }}

# Добавляем сервер в хосты, которым можно доверять
    - name: Add server to SSH_SECRET_KEY
      run: |
        ssh-keyscan -H ${{ secrets.SSH_SERVER }} >> ~/.ssh/SSH_SECRET_KEY
 
# Заливаем файлы
    - name: Copy files to the server
      if: runner.os == 'Windows'
      run: |
        rsync -avz --delete ./ ${{ secrets.USER }}@${{ secrets.SSH_SERVER }}:/home/tivarus/app
 
